export const LEMGEN_MODELS = [
  {
    id: 'gpt-image-2',
    name: 'GPT Image 2',
    mediaType: 'image',
    strengths: ['high fidelity', 'text rendering', 'product and editorial images'],
    aspectRatios: ['auto', '1:1', '16:9', '9:16', '4:3', '3:4'],
    resolutions: ['1K', '2K', '4K'],
    maxReferenceImages: 4,
  },
  {
    id: 'nano-banana',
    name: 'Nano Banana',
    mediaType: 'image',
    strengths: ['fast drafts', 'stylized images', 'reference-aware editing'],
    aspectRatios: ['auto', '1:1', '16:9', '9:16', '4:3', '3:4'],
    resolutions: ['1K', '2K'],
    maxReferenceImages: 3,
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    mediaType: 'image',
    strengths: ['cinematic style', 'portraits', 'fashion', 'illustration'],
    aspectRatios: ['auto', '1:1', '16:9', '9:16', '3:2', '2:3'],
    resolutions: ['1K', '2K'],
    maxReferenceImages: 1,
  },
  {
    id: 'seedance',
    name: 'Seedance',
    mediaType: 'video',
    strengths: ['text-to-video', 'image-to-video', 'motion design'],
    aspectRatios: ['auto', '16:9', '9:16', '1:1'],
    resolutions: ['480p', '720p', '1080p', '4k'],
    durations: [4, 5, 8, 10, 15],
    maxReferenceImages: 2,
  },
  {
    id: 'veo',
    name: 'Veo',
    mediaType: 'video',
    strengths: ['native audio', 'cinematic video', 'short commercial clips'],
    aspectRatios: ['auto', '16:9', '9:16'],
    resolutions: ['720p', '1080p', '4k'],
    durations: [4, 6, 8],
    maxReferenceImages: 2,
  },
];
